title: Safe Journey Sanctum
description: Peer-led, compassionate support for individuals navigating nonordinary states of consciousness.
theme: minimal-mistakes-jekyll

url: "https://psychedelicsocietyofkansascity.github.io"
baseurl: "/" # Only if your GitHub repo isn't user.github.io

repository: psychedelicsocietyofkansascity/sjs-org

# Optional settings
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
minimal_mistakes_skin: "dark"
sass:
  style: compressed

# Default values for posts and pages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: false
      css: "/assets/css/custom.css" # Custom styles
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      css: "/assets/css/custom.css" # Custom styles
